export enum ModalType {
  EDIT_MUSIC = 'EDIT_MUSIC',
  CREATE_MUSIC = 'CREATE_MUSIC',
  DELETE_MUSIC = 'DELETE_MUSIC',
  CREATE_CHANNEL = 'CREATE_CHANNEL',
  EDIT_CHANNEL = 'EDIT_CHANNEL',
  DELETE_CHANNEL = 'DELETE_CHANNEL',
}
